import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import sitemap from 'vite-plugin-sitemap';

// sitemap.xml is auto-generated by vite-plugin-sitemap at build time — do not hand-edit.

// Blog: `scripts/build-blog-registry.ts` (prebuild/predev) parses `.mdx` with gray-matter in Node and writes
// `registry-data.json`; `registry.ts` imports that JSON so the client bundle never loads gray-matter/Buffer.
// Bodies still render through `marked`. No `@mdx-js/rollup` — keeps `.mdx` authoring without MDX→React compile.

const staticRoutes = [
  '/',
  '/talent',
  '/hire',
  '/review',
  '/for-teams',
  '/join',
  '/about',
  '/contact',
  '/how-it-works',
  '/privacy',
  '/terms',
  '/login',
  '/guides/pricing-2025',
  '/hire/memphis',
  '/hire/nashville',
  '/hire/new-orleans',
  '/concierge',
  '/hire/match-confirmed',
  '/blog',
  '/dashboard/briefs',
  '/talent/aisha-laurent',
  '/locations/memphis',
];

const blogSlugs = [
  'recipe-development-costs',
  'food-stylist-cost',
  'private-chef-cost',
  'sk-verified',
  'how-ai-matches-chefs',
  'culinary-consultant-guide',
  'culinex-alternative',
  'memphis-culinary-talent',
  'nashville-culinary-talent',
  'new-orleans-culinary-talent',
];

const dynamicRoutes = [...staticRoutes, ...blogSlugs.map((s) => `/blog/${s}`)];

const priority = Object.fromEntries(
  dynamicRoutes.map((route) => {
    let p = 0.5;
    if (route === '/') p = 1.0;
    else if (route.startsWith('/hire/')) p = 0.8;
    else if (route === '/talent') p = 0.8;
    else if (route === '/for-teams') p = 0.8;
    else if (route.startsWith('/blog/')) p = 0.6;
    return [route, p] as const;
  }),
);

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    sitemap({
      hostname: 'https://spicekrewe.com',
      dynamicRoutes,
      exclude: ['/admin', '/admin/health', '/hire/success'],
      changefreq: 'monthly',
      priority,
    }),
  ],
  optimizeDeps: {
    exclude: ['lucide-react'],
  },
  server: {
    // Forward API routes to `vercel dev` (default :3000) when running `vite` alone.
    proxy: {
      '/api': { target: 'http://127.0.0.1:3000', changeOrigin: true },
    },
  },
});
