import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import sitemap from 'vite-plugin-sitemap';

// sitemap.xml is auto-generated by vite-plugin-sitemap at build time — do not hand-edit.

// Blog pipeline: `src/content/blog/*.mdx` is loaded as raw text via `import.meta.glob(..., { query: '?raw' })`
// in `registry.ts`, frontmatter is parsed with `gray-matter` (YAML → metadata), and bodies render through `marked`.
// No `@mdx-js/rollup` layer — avoids compiling MDX to React components while keeping `.mdx` authoring.

const staticRoutes = [
  '/',
  '/talent',
  '/hire',
  '/for-teams',
  '/join',
  '/about',
  '/contact',
  '/how-it-works',
  '/privacy',
  '/terms',
  '/login',
  '/guides/pricing-2025',
  '/hire/recipe-developer',
  '/hire/food-stylist',
  '/hire/culinary-consultant',
  '/hire/memphis',
  '/hire/nashville',
  '/hire/new-orleans',
  '/hire/match-confirmed',
  '/blog',
  '/dashboard/briefs',
  '/talent/aisha-laurent',
  '/locations/memphis',
];

const blogSlugs = [
  'recipe-development-costs',
  'food-stylist-cost',
  'private-chef-cost',
  'sk-verified',
  'how-ai-matches-chefs',
  'culinary-consultant-guide',
  'culinex-alternative',
  'memphis-culinary-talent',
  'nashville-culinary-talent',
  'new-orleans-culinary-talent',
];

const dynamicRoutes = [...staticRoutes, ...blogSlugs.map((s) => `/blog/${s}`)];

const priority = Object.fromEntries(
  dynamicRoutes.map((route) => {
    let p = 0.5;
    if (route === '/') p = 1.0;
    else if (route.startsWith('/hire/')) p = 0.8;
    else if (route === '/talent') p = 0.8;
    else if (route === '/for-teams') p = 0.8;
    else if (route.startsWith('/blog/')) p = 0.6;
    return [route, p] as const;
  }),
);

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    sitemap({
      hostname: 'https://spicekrewe.com',
      dynamicRoutes,
      exclude: ['/admin', '/admin/health', '/hire/success'],
      changefreq: 'monthly',
      priority,
    }),
  ],
  optimizeDeps: {
    exclude: ['lucide-react'],
  },
  server: {
    // Forward API routes to `vercel dev` (default :3000) when running `vite` alone.
    proxy: {
      '/api': { target: 'http://127.0.0.1:3000', changeOrigin: true },
    },
  },
});
